version: 2
updates:
- package-ecosystem: docker
  directory: "/kismet/2019-07-R2"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
